# Generated by Django 6.0.7 on 2026-07-22 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('icon', models.CharField(blank=True, default='💪', help_text='Un emoji que representa la categoria', max_length=10, verbose_name='Icono (emoji)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='core.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RoutineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')], verbose_name='Dia')),
                ('weight', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Peso (kg)')),
                ('sets', models.PositiveIntegerField(default=3, verbose_name='Series')),
                ('reps', models.PositiveIntegerField(default=10, verbose_name='Repeticiones')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercise', verbose_name='Ejercicio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejercicio de rutina',
                'verbose_name_plural': 'Ejercicios de rutina',
                'ordering': ['day', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('weight', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Peso (kg)')),
                ('sets', models.PositiveIntegerField(default=3, verbose_name='Series')),
                ('reps', models.PositiveIntegerField(default=10, verbose_name='Repeticiones')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercise', verbose_name='Ejercicio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de entrenamiento',
                'verbose_name_plural': 'Registros de entrenamiento',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
