# Generated by Django 6.0.7 on 2026-07-22 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio mensual')),
                ('currency', models.CharField(choices=[('ARS', 'Peso argentino (ARS)'), ('PYG', 'Guarani (PYG)'), ('BRL', 'Real (BRL)'), ('UYU', 'Peso uruguayo (UYU)'), ('CLP', 'Peso chileno (CLP)'), ('COP', 'Peso colombiano (COP)'), ('PEN', 'Sol (PEN)'), ('MXN', 'Peso mexicano (MXN)')], default='ARS', max_length=3, verbose_name='Moneda')),
                ('trial_days', models.PositiveIntegerField(default=7, verbose_name='Dias de prueba gratis')),
                ('mp_access_token', models.CharField(blank=True, help_text='Se obtiene en Mercado Pago > Tus integraciones > Credenciales', max_length=255, verbose_name='Access Token de Mercado Pago')),
                ('mp_public_key', models.CharField(blank=True, max_length=255, verbose_name='Public Key de Mercado Pago')),
            ],
            options={
                'verbose_name': 'Configuracion',
                'verbose_name_plural': 'Configuracion',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('currency', models.CharField(default='ARS', max_length=3, verbose_name='Moneda')),
                ('months', models.PositiveIntegerField(default=1, verbose_name='Meses')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10, verbose_name='Estado')),
                ('manual', models.BooleanField(default=False, verbose_name='Activacion manual del admin')),
                ('mp_preference_id', models.CharField(blank=True, max_length=100)),
                ('mp_payment_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_ends', models.DateField(verbose_name='Fin de prueba gratis')),
                ('paid_until', models.DateField(blank=True, null=True, verbose_name='Pagado hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripcion',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
    ]
