# Generated by Django 6.0.7 on 2026-07-23 00:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfig_payment_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='kind',
            field=models.CharField(choices=[('strength', 'Fuerza (peso, series y repeticiones)'), ('cardio', 'Cardio (minutos y distancia)')], default='strength', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='routineitem',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distancia (km)'),
        ),
        migrations.AddField(
            model_name='routineitem',
            name='duration_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duracion (min)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='exempt',
            field=models.BooleanField(default=False, verbose_name='Liberado de pago'),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distancia (km)'),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='duration_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duracion (min)'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='DailyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('routine_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='core.routineitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Check diario',
                'verbose_name_plural': 'Checks diarios',
                'constraints': [models.UniqueConstraint(fields=('routine_item', 'date'), name='unique_check_per_day')],
            },
        ),
    ]
