# Generated by Django 6.0.7 on 2026-08-05 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exercise_kind_routineitem_distance_km_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Zona del cuerpo', 'verbose_name_plural': 'Zonas del cuerpo'},
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#a3e635', help_text='Color de la zona en la app (hex, ej: #a3e635)', max_length=7, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='dailycheck',
            name='sets_done',
            field=models.PositiveIntegerField(default=0, verbose_name='Series completadas'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('bodyweight', 'Calistenia (peso corporal)'), ('barbell', 'Barra'), ('dumbbell', 'Mancuerna'), ('machine', 'Maquina'), ('cable', 'Polea'), ('kettlebell', 'Kettlebell'), ('band', 'Banda elastica'), ('other', 'Otro')], default='bodyweight', max_length=12, verbose_name='Equipamiento'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=12, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='profile',
            name='days_per_week',
            field=models.PositiveIntegerField(default=3, verbose_name='Dias por semana'),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_rest',
            field=models.PositiveIntegerField(default=60, verbose_name='Descanso preferido (seg)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('hipertrofia', 'Ganar masa muscular'), ('fuerza', 'Ganar fuerza'), ('perder_grasa', 'Bajar de peso / definir'), ('resistencia', 'Resistencia y tonificar')], default='hipertrofia', max_length=15, verbose_name='Objetivo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=12, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='routineitem',
            name='note',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='routineitem',
            name='rest_seconds',
            field=models.PositiveIntegerField(default=60, verbose_name='Descanso entre series (seg)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='💪', help_text='Un emoji que representa la zona del cuerpo', max_length=10, verbose_name='Icono (emoji)'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='core.category', verbose_name='Zona del cuerpo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT'),
        ),
    ]
