# Generated by Django 6.0.7 on 2026-09-28 12:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_options_category_color_category_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutinePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', 'Semanal'), ('monthly', 'Mensual')], default='weekly', max_length=10, verbose_name='Periodo')),
                ('label', models.CharField(blank=True, max_length=60, verbose_name='Nombre')),
                ('started_at', models.DateField(verbose_name='Inicio')),
                ('ended_at', models.DateField(default=datetime.date.today, verbose_name='Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan guardado',
                'verbose_name_plural': 'Planes guardados',
                'ordering': ['-ended_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RoutinePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')], verbose_name='Dia')),
                ('weight', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Peso (kg)')),
                ('sets', models.PositiveIntegerField(default=3, verbose_name='Series')),
                ('reps', models.PositiveIntegerField(default=10, verbose_name='Repeticiones')),
                ('duration_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duracion (min)')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distancia (km)')),
                ('rest_seconds', models.PositiveIntegerField(default=60, verbose_name='Descanso entre series (seg)')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='Nota')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercise', verbose_name='Ejercicio')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.routineplan')),
            ],
            options={
                'verbose_name': 'Ejercicio de plan guardado',
                'verbose_name_plural': 'Ejercicios de plan guardado',
                'ordering': ['day', 'order', 'id'],
            },
        ),
    ]
