# Generated by Django 6.0.7 on 2026-09-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_routineplan_routineplanitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bench_1rm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='1RM Press de banca (kg)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='deadlift_1rm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='1RM Peso muerto (kg)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='core.exercise', verbose_name='Ejercicios favoritos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='squat_1rm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='1RM Sentadilla (kg)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogramos (kg)'), ('lb', 'Libras (lb)')], default='kg', max_length=2, verbose_name='Unidad de peso'),
        ),
    ]
