# Generated by Django 6.0.7 on 2026-09-29 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_bench_1rm_profile_deadlift_1rm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video',
            field=models.FileField(blank=True, help_text='Video corto mostrando como se hace el ejercicio. Si hay video, se muestra en vez de la imagen.', null=True, upload_to='exercise_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4'])], verbose_name='Video (mp4, 15 seg. max.)'),
        ),
    ]
